### ISSUE TITLE
home mode error 

### ISSUE THREAD

**Issue by ghost** [JoseVarelaP/-OITG-ITGPs2-Restoration-Project#1]
error in ITG theme while switching to home mode and going back to the title screen in any method
sm log reports "[string "in"]:2: bad argument #3 to `diffuse' (number expected, got no value)"

**Comment by JoseVarelaP** [comment]
Could possibly be anything from ScreenTitleMenu, however, suddenly it got fixed in a way, and it works normally, but still not sure being fixed at all.
